---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qotm
spec:
  replicas: 3
  strategy:
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.1
        imagePullPolicy: Always
        ports:
        - name: http-api 
          containerPort: 5000
